### ISSUE TITLE
Option `remove` not implemented?

### ISSUE THREAD

**Issue by jrson83** [enpitsuLin/rehype-prism-diff#1]
Thanks for making this great plugin. I really enjoy `rehype-prism-plus` but it's definitely missing this feature.
I use Deno and tried to use the Options `remove`, which I saw when opening the `index.d.ts`.

```ts
import type { Plugin } from 'https://esm.sh/v89/unified@10.1.2/index.d.ts';
import type { Element } from 'https://esm.sh/v89/@types/hast@2.3.4/index.d.ts';
export interface Options {
    /** emove the first character which used to mark */
    remove?: boolean;
}
declare const rehypePrismDiff: Plugin<[Options?], Element>;
export default rehypePrismDiff;
```

Since it was not working I checked the source code and saw this option is not integrated yet?
If it's okay, I will implement this feature and create a PR.

**Comment by enpitsuLin** [comment]
yes, it was not implemented
Actually, the Plugin option has even been removed, I forgot to publish it🤣
if you want implement it just feel free

**Comment by enpitsuLin** [comment]
this option and some other option was implemented, but not released yet.

you can checkout later, I'm working on some ci thing and write new readme, thanks for issue to remind me this project should be improved

**Comment by jrson83** [comment]
Great you removed the old class package. I saw you created typings for it but the PR was never merged. I wasn't very happy with that old package and also replaced it. Didn't have time to write tests yet, else I would have created a PR.

Thank you. I will test it out.
