### ISSUE TITLE
Remove not working

### ISSUE THREAD

**Issue by jrson83** [enpitsuLin/rehype-prism-diff#2]
Hey, sorry to open again another issue, but I tried v1.1.2 and `remove` doesn't remove `+` or `-` for me using:

```js
[rehypePrismDiff, { remove: true }],
```

**Comment by jrson83** [comment]
Really strange, suddenly it is working. Thanks again for the update!

**Comment by enpitsuLin** [comment]
In fact, this feature does have the expected bugs

It will remove multiple times if there are multiple mark characters one line, or removing characters incorrectly.

eg.
```js
let count = 0;
+count -= 1; 
count += 1;  // => both will became `count = 1`
```
Tbh, I don't have a good idea to solve it, this probably why I didn't implement this feature at the time😅.

I'll spend some time trying to figure it out, or if you have any ideas feel free to contribute!

**Comment by jrson83** [comment]
What I noticed is that when you use showLineNumbers with rehype-prism-plus, the remove does not work. I agree, it is hard to take all this into account. If I have an idea I'll let you know :laughing:
